#
# Copyright (C) 2014-2015 Maarten Deprez <<A HREF="https://lists.openwrt.org/cgi-bin/mailman/listinfo/openwrt-devel">deprez.maarten at gmail.com</A>>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Huawei NCM
LUCI_DEPENDS:=+huawei-ncm

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
